service: aggregator-nhs-ed-wait-times

frameworkVersion: '3'

custom:
  wsgi:
    app: api.app

provider:
  name: aws
  runtime: python3.10
  region: eu-west-1

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
